### ISSUE TITLE
Add ability to "append" to existing firefox prefs

### ISSUE THREAD

**Issue by rpappalax** [mozilla-services/shavar-e2e-tests#33]
see for example, prefs.ini line 13

**Comment by rbillings** [comment]
Firefox prefs have been addressed- I believe this issue can be closed. @rpappalax ?

**Comment by rpappalax** [comment]
@rbillings i know that luke, francois updated the prefs but the issue here was that we write prefs to firefox in one of the following ways:
1. add a new pref
2. replace a pref w/ a new value
however, there was a third case in which francois wanted to us to 
3. retain an existing (default) value of a pref and APPEND' to it.  
this is tricky, cause we would literally have to launch firefox to grab the existing pref then modify it and re-write it to firefox.
