### ISSUE TITLE
Add test verifying Strict list

### ISSUE THREAD

**Issue by rbillings** [mozilla-services/shavar-e2e-tests#43]
Strict list = base list + content list (purpose is to serve content-related things)
https://mozilla.github.io/tracking-test/full.html (only shows the shield when the strict list is enabled)
Would only be testing content manually to make sure certain content providers are blocked.

**Comment by rpappalax** [comment]
@rbillings I'm trying to figure out which test this would be??
https://github.com/rbillings/shavar-e2e-tests/tree/master/tests

**Comment by rbillings** [comment]
@rpappalax I don't understand. This issue is to write a test verifying the strict list. These are the specific steps:
1. Create a new Nightly profile.
2. Go into about:preferences#privacy and set Tracking Protection to Always.
3. Click on Change Block List and select _strict_ protection.
4. Open http://cnn.com and confirm the TP doorhanger shows up.

**Comment by rpappalax** [comment]
@rbillings didn't mean to be confusing.  i just thought we had already written all the tests and were now filling them out but it sounds like this is a new test we haven't started yet?

**Comment by rbillings** [comment]
This is a new test that has not been started yet, correct.

**Comment by rpappalax** [comment]
👍

**Comment by rpappalax** [comment]
summary notes (email from francois):
Here's a test page to verify the strict list (it uses gravatar.com) is in use or not:
 https://mozilla.github.io/tracking-test/full.html

standard list in use: black cat
strict list in use: orange one
