### ISSUE TITLE
Fix: test_safe_browsing_contains_expected_files

### ISSUE THREAD

**Issue by rpappalax** [mozilla-services/shavar-e2e-tests#63]
I just ran the filesize test on STAGE and PROD and noticed that we have 1 pass and 1 fail.
It looks to me like the wrong files set is being served.  Perhaps next week we can run this together and/or separately manually to ensure that what I'm observing is true.

I tried using about:url-classifier trigger, to re-trigger loading from shavar, but it didn't do any good.

**[1] test_safebrowsing_contains_expected_files**

--test-env=stage --pref-set=moztestpub

FAIL - because it's missing the "expected":

    moztestpub-track-digest256 and
    moztestpub-trackwhite-digest256 files. 

instead, it is downloading mozstd-track-digest256.

--test-env=prod --pref-set=base

FAIL - because it's missing the "expected":

    content-track-digest256 file.

note:  all the other expected files are there

**[2] test_safebrowsing filesize**

--test-env=stage --pref-set=moztestpub

PASS

--test-env=prod --pref-set=moztestpub

PASS

**Comment by groovecoder** [comment]
I did a `curl` on the server, and the stage server seems to include the expected `moztestpub-*` list files:
```
(shavar)groovetop:shavar lcrouch$ curl -d "" https://shavar.stage.mozaws.net/list
ads-track-digest256
allow-flashallow-digest256
analytics-track-digest256
base-track-digest256
baseeff-track-digest256
basew3c-track-digest256
block-flash-digest256
block-flashsubdoc-digest256
content-track-digest256
contenteff-track-digest256
contentw3c-track-digest256
except-flash-digest256
except-flashallow-digest256
except-flashinfobar-digest256
except-flashsubdoc-digest256
except-infobars-digest256
mozfull-track-digest256
mozfullstaging-track-digest256
mozplugin-block-digest256
mozpub-track-digest256
mozstd-track-digest256
mozstd-trackwhite-digest256
mozstdstaging-track-digest256
mozstdstaging-trackwhite-digest256
moztestpub-track-digest256
moztestpub-trackwhite-digest256
social-track-digest256
```

**Comment by groovecoder** [comment]
And a curl to the prod server shows `content-track-digest256` list file:
```
(shavar)groovetop:shavar lcrouch$ curl -d "" https://shavar.prod.mozaws.net/list
ads-track-digest256
allow-flashallow-digest256
analytics-track-digest256
base-track-digest256
baseeff-track-digest256
basew3c-track-digest256
block-flash-digest256
block-flashsubdoc-digest256
content-track-digest256
contenteff-track-digest256
contentw3c-track-digest256
except-flash-digest256
except-flashallow-digest256
except-flashinfobar-digest256
except-flashsubdoc-digest256
mozfull-track-digest256
mozfullstaging-track-digest256
mozplugin-block-digest256
mozplugin2-block-digest256
mozpub-track-digest256
mozstd-track-digest256
mozstd-trackwhite-digest256
mozstdstaging-track-digest256
mozstdstaging-trackwhite-digest256
social-track-digest256
```

**Comment by rpappalax** [comment]
ckolos was able to manually force an update to S3.  this does update the moztestpub files in S3, but somehow they never make it to the safebrowsing folder:
----------------------unique--------------------------
['google4', 'block-flashsubdoc-digest256', 'test-harmful-simple', 'except-flashallow-digest256', 'except-flashsubdoc-digest256', 'allow-flashallow-digest256', 'test-malware-simple', 'block-flash-digest256', 'test-trackwhite-simple', 'base-track-digest256', 'except-flashinfobar-digest256', 'test-track-simple', 'test-unwanted-simple', 'except-flash-digest256', 'mozstd-trackwhite-digest256', 'test-phish-simple', 'test-block-simple']
----------------------expected------------------------
['test-track-simple', 'moztestpub-track-digest256', 'test-trackwhite-simple', 'moztestpub-trackwhite-digest256']

**Comment by rbillings** [comment]
Note: need to verify now that stage has been fixed
