### ISSUE TITLE
Trigger automation on github list checkin

### ISSUE THREAD

**Issue by rpappalax** [mozilla-services/shavar-e2e-tests#66]
PURPOSE
Shavar automation will be triggered on shavar service deployments.
However, we'd also like to have automation execute every time someone makes a check-in to one of the shavar list repos, i.e.:
https://github.com/mozilla-services/shavar-prod-lists

TBD
check w/ groovecoder if there's a way we could also have a comparable list(s) checked into mozilla-services/shavar-test-lists so we can do proper verification on stage.

**Comment by rbillings** [comment]
GitHook trigger list:
1) On new list commit
2) On shavar server commit
3) On shavar config commit
4) On shavar service deployment (stage, prod)
