### ISSUE TITLE
README

### ISSUE THREAD

**Issue by rpappalax** [mozilla-services/shavar-e2e-tests#67]
We need to create a README:
* pre-reqs: knowledge of pytest, selenium, Docker, tracking protection
* install: python, pytest, Docker
* execute the tests

NOTES:
manual execution steps are documented in TestRail.  If you need permission, please file an issue here.

REFERENCE
* TestRail
* (internal only) Mana page references to shavar system

**Comment by rbillings** [comment]
I updated the README directly: https://github.com/mozilla-services/shavar-e2e-tests/blob/master/README.md

The only omission was the Mana page as I wasn't sure linking to a private page is a good idea. Would it be better to mention the page without a link? Or add a link that is inaccessible to many?

**Comment by rbillings** [comment]
Added link to Mana.  More readme updates will be filed as separate issues.
