### ISSUE TITLE
List filenames for shavar-test-lists repo should match shavar-prod-lists

### ISSUE THREAD

**Issue by rpappalax** [mozilla-services/shavar-e2e-tests#68]
shavar-prod-lists
disconnect-prodlist.json, disconnect-entitylist.json

shavar-test-lists
track.json, trackwhite.json

**Comment by rbillings** [comment]
@rpappalax did we agree that we do not need to change the filenames because of the specific mention of prod? or did we agree to make it:
disconnect-stagelist.json & disconnect-entitylist.json
?
